FROM python:3.8

# Set the working directory to /app
WORKDIR /issuer
ADD ./issuer/requirements.txt /issuer/requirements.txt

# Install any needed packages
RUN pip install -r /issuer/requirements.txt

# Copy the current directory contents into the container at /app
ADD ./issuer /issuer

EXPOSE 8000