FROM python:3.8

# Set the working directory to /app
WORKDIR /multitenant
ADD ./multitenant/requirements.txt /multitenant/requirements.txt

# Install any needed packages
RUN pip install -r  /multitenant/requirements.txt

# Copy the current directory contents into the container at /app
ADD ./multitenant /multitenant

EXPOSE 8002